// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication4.Models;

namespace WebApplication4.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20181214082424_Abc")]
    partial class Abc
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication4.Models.DocGia", b =>
                {
                    b.Property<int>("MaKH")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GioiHanSach");

                    b.Property<int>("GioiHanTG");

                    b.Property<int>("LoaiDG");

                    b.Property<int>("SoSachMuon");

                    b.HasKey("MaKH");

                    b.ToTable("Docgias");
                });

            modelBuilder.Entity("WebApplication4.Models.QuanLy", b =>
                {
                    b.Property<int>("MaQL")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("MaQL");

                    b.ToTable("Quanlys");
                });

            modelBuilder.Entity("WebApplication4.Models.Sach", b =>
                {
                    b.Property<int>("MaSach")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DanhGia");

                    b.Property<string>("GioiThieu");

                    b.Property<string>("Hinh");

                    b.Property<int>("MaChiNhanh");

                    b.Property<string>("NamXuatBan");

                    b.Property<string>("NhaXuatBan");

                    b.Property<string>("SoLuong");

                    b.Property<string>("TacGia");

                    b.Property<string>("TuaSach");

                    b.HasKey("MaSach");

                    b.HasIndex("MaChiNhanh");

                    b.ToTable("Sachs");
                });

            modelBuilder.Entity("WebApplication4.Models.ThuThu", b =>
                {
                    b.Property<int>("MaTT")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaChiNhanh");

                    b.HasKey("MaTT");

                    b.HasIndex("MaChiNhanh");

                    b.ToTable("ThuThus");
                });

            modelBuilder.Entity("WebApplication4.Models.ThuVien", b =>
                {
                    b.Property<int>("MaChiNhanh")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi");

                    b.Property<string>("TenChiNhanh");

                    b.HasKey("MaChiNhanh");

                    b.ToTable("ThuViens");
                });

            modelBuilder.Entity("WebApplication4.Models.Sach", b =>
                {
                    b.HasOne("WebApplication4.Models.ThuVien", "ThuVien")
                        .WithMany()
                        .HasForeignKey("MaChiNhanh")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApplication4.Models.ThuThu", b =>
                {
                    b.HasOne("WebApplication4.Models.ThuVien", "ThuVien")
                        .WithMany()
                        .HasForeignKey("MaChiNhanh")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
